#cs ----------------------------------------------------------------------------

 AutoIt Version: 3.3.14.2
 Author:         t-knapp

 Script Function:
	Functions for GUI (tinc join, tinc status/connect)

#ce ----------------------------------------------------------------------------

#include-once
#include "Globals.au3"

#Region Functions for tinc start / tinc status GUI
Global $bIsTincStartGuiCreated = False ; Create once and hide/show on demand
Global $hTincDisconnectButton
Func guiTincStart($sNetworkName)
	If Not $bIsTincStartGuiCreated Then
		ConsoleWrite("Creating tinc start GUI" & @CRLF)
		Local $iWidth = 600
		Local $iHeight = 400

		Local $iButtonWidth = 125
		Local $iButtonHeight = 24

		Global $hTincStartGui = GUICreate("Tinc Status '" & $sNetworkName & "'", $iWidth, $iHeight, @DesktopWidth/2 - $iWidth/2, @DesktopHeight/2 - $iHeight/2, $WS_CAPTION + $WS_MINIMIZEBOX + $WS_SYSMENU); + $WS_THICKFRAME)
		$hTincStartLog = GUICtrlCreateEdit("", 5, 5, $iWidth - 10, $iHeight - 15 - $iButtonHeight, $ES_AUTOVSCROLL + $WS_VSCROLL)
		GUICtrlSetFont($hTincStartLog, 8.5,0, 0, "Courier New")
		$hTincDisconnectButton = GUICtrlCreateButton("Disconnect", $iWidth - 5 - $iButtonWidth, $iHeight - $iButtonHeight - 5, $iButtonWidth, $iButtonHeight)
		GUICtrlSetOnEvent($hTincDisconnectButton, "tinc_stop")

		$bIsTincStartGuiCreated = True

		GUISetOnEvent($GUI_EVENT_CLOSE, "guiTincHide", $hTincStartGui)
	EndIf
	GUISetState(@SW_SHOW, $hTincStartGui)
EndFunc

Func guiTincHide()
	If $bIsTincStartGuiCreated Then
		GUISetState(@SW_HIDE, $hTincStartGui)
	EndIf
EndFunc

Func guiTincShow()
	If $bIsTincStartGuiCreated Then
		GUISetState(@SW_SHOW, $hTincStartGui)
	EndIf
EndFunc
#EndRegion

#Region Tinc Join GUI
Global $gTincJoinOutput = ""
Global $gIsTincJoinGuiCreated = False
Global $guiNetwork
Func joinNetworkGUI()
	ConsoleWrite($gIsTincJoinGuiCreated)
	If $gIsTincJoinGuiCreated == False Then
		$guiWidth = 600
		$guiHeight = 400
		$guiNetwork = GUICreate("Tinc Join Network", $guiWidth, $guiHeight, @DesktopWidth/2 - $guiWidth/2, @DesktopHeight/2 - $guiHeight/2)
		GUICtrlCreateLabel("Enter the invitation code generated by the tinc server.", 5, 5)
		GUICtrlCreateLabel("Invitation code:", 5, 30)

		Global $idInputCode  = GUICtrlCreateInput("", 82, 27, 430)
		Local $idButtonJoin = GUICtrlCreateButton("Join", 515, 25, 50)
		GUICtrlSetOnEvent($idButtonJoin, "tinc_join")

		$idMyedit = GUICtrlCreateEdit("", 5, 60, $guiWidth-10, 300, $ES_AUTOVSCROLL + $WS_VSCROLL)

		GUISetOnEvent($GUI_EVENT_CLOSE, "joinNetworkGUI_exit")
		$gIsTincJoinGuiCreated = True
	EndIf
	GUISetState(@SW_SHOW, $guiNetwork)
EndFunc   ;==>joinNetworkGUI

Func joinNetworkGUI_exit()
	GUISetState(@SW_HIDE, $guiNetwork)
EndFunc   ;==>joinNetworkGUI_exit

#EndRegion
